/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cradle.spring.xx.app;


import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

//import java.util.List;

@SpringBootApplication
public class App {

    public String getGreeting() {
        return "Let's try spring poot RestFul services";
    }

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());
        SpringApplication.run(App.class, args);
    }
}
