/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cradle.spring.xx.app;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        // Tämä testattu onnistuneesti 26.11.2019
        App classUnderTest = new App();
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
        assertEquals("Let's try spring poot RestFul services", classUnderTest.getGreeting());
    }
}
